spring:
  data:
    jpa:
      url: jdbc:mariadb://localhost:3306/db1
      username: root
      password: root
  elastic:
    url:
      - https://elastic01.com
      - https://elastic02.com
      - https://elastic03.com
kubernetes:
  service: http://another-service:8080
  service-without-protocol: this-that-service:8686
google:
  url: https://www.google.com
twitter:
  url: https://www.twitter.com
instagram:
  url: https://www.instagram.com
