name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make

    - name: Test
      run: ./eyeball -f subject.yml -c demo.yml -p "^(jdbc:mariadb|https?)://(.*)(:\\d+)?(\/.*)?$" -p "^([a-zA-Z0-9.-])+(:\\d{2,4})$"
