name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install automake

    - name: Build
      run: make
      env:
        CI: true
